### ISSUE TITLE
Question regarding CSR publishing

### ISSUE THREAD

**Issue by EmilOlovsson** [teslamotors/fleet-telemetry#112]
I submitted a CSR Feb 7:th and I'm still waiting for approval. I attached the Application client_id and a short description of the fields I need and why. The CSR has also passed the tools/check_csr.sh script.

- How long does confirmation usually take?

**Comment by Bre77** [comment]
It took me about 40 days to get a response, at which point I did have to update my CSR to pass the new check script. That was 10 days ago and I still haven't actually been issued a certificate.

I believe others have got their certificates sooner.

The only comment I've seen is they are ramping up the process, but I'd set your expectations to 1-2 months.

**Comment by KarlF-KFLOE** [comment]
It's definitely an exercise in patience but having an officially supported solution will be worth the wait. The addition of partner OAuth has already made things much easier for us. Hopefully pricing for large fleets will be sustainable long-term. 

We originally submitted our CSR on 12/12, heard back on 2/9 and resubmitted to pass the check script on 2/10. All in all, we've been trying to make progress since late October.

Has anyone actually confirmed they have fleet-telemetry working end-to-end?

**Comment by patrickdemers6** [comment]
Sorry for the long wait times - there have been a lot of moving parts. Hopefully we can keep the delays to a minimum going forward.

fleet-telemetry is just starting to be used by the general public so the documentation still needs some work. Until that happens, here is a post I created walking through the entire configuration process.

https://dev.to/patrickdemers6/fleet-telemetry-streaming-data-from-your-tesla-2i97

**Comment by bassmaster187** [comment]
> https://dev.to/patrickdemers6/fleet-telemetry-streaming-data-from-your-tesla-2i97

Your docs are very helpful!

On my server there is already an apache running on port 443 with a certbot. Is it possible to run the telemetry server on a different port or how can I solve the problem? Or should I use apache as a proxy for the telemetry server?

**Comment by EmilOlovsson** [comment]
I've gotten a confirmation from Tesla that my CSR has been published. Thanks everyone for replying to this thread!

> Sorry for the long wait times - there have been a lot of moving parts. Hopefully we can keep the delays to a minimum going forward.
> 
> fleet-telemetry is just starting to be used by the general public so the documentation still needs some work. Until that happens, here is a post I created walking through the entire configuration process.
> 
> https://dev.to/patrickdemers6/fleet-telemetry-streaming-data-from-your-tesla-2i97

Great docs!

> > https://dev.to/patrickdemers6/fleet-telemetry-streaming-data-from-your-tesla-2i97
> 
> Your docs are very helpful!
> 
> On my server there is already an apache running on port 443 with a certbot. Is it possible to run the telemetry server on a different port or how can I solve the problem? Or should I use apache as a proxy for the telemetry server?

I use nginx as a reverse proxy.
