### ISSUE TITLE
Drivers can remove fleet-telemetry config

### ISSUE THREAD

**Issue by stx** [teslamotors/fleet-telemetry#116]
Drivers can send a DELETE request to `fleet_telemetry_config` and delete the config.

This is strange because only Owners can POST requests to `fleet_telemetry_config`.

If only owners can create, you would expect only owners to be able to delete.

**Comment by aaronpkahn** [comment]
Good point. That is inconsistent behavior.  We'll support DRIVER access on the POST endpoint soon
