### ISSUE TITLE
Fleet Telemetry vs. Fleet API

### ISSUE THREAD

**Issue by davidlinn** [teslamotors/fleet-telemetry#137]
I'm building a third-party service that needs to pull the location and heading of a user's vehicle once or twice daily. I'm currently calling wake_up and then waiting until the vehicle_data API is available. I've found that waking up is not always reliable and I'm worried that it could be contributing to battery drain. Would the fleet telemetry API be better for my use case? 

Also, I notice that TeslaPy has a [stream() function](https://github.com/tdorssers/TeslaPy/blob/master/teslapy/__init__.py#L464), has anyone tried using that?

**Comment by patrickdemers6** [comment]
Please try not to wake vehicles unnecessarily as it will drain the vehicle's battery. fleet-telemetry allows the vehicle to stream data directly to your server. This will make it so you don't have to worry about vehicle connectivity. Whenever data is available, you'll receive it.
