### ISSUE TITLE
domain, region & server question

### ISSUE THREAD

**Issue by neilmorley** [teslamotors/fleet-telemetry#148]
Hi,

I've only just sent my csr for approval so I haven't setup my server yet but have a couple of questions please.

1) If I want to seperate my prod vehicles from test vehicles (where test vehicle data is streamed to server A and prod vehicle data is streamed to Server B) can I use the same 'Application' to do this?

2) Can the same certificate for ourdomain.com be registered at both regional endpoints (I have test vehicles in both North US and European regions) and can I stream data from both regions to the same server?

3) I am likely to need to introduce at least one more domain, but possibly more. Do I need a seperate 'Application' for each domain and would I be able to stream the data for multiple domains to the same server (Eg. ourdomain.com & theirdomain.com both streaming to server A)?

Thankyou

**Comment by Bre77** [comment]
These are answers based on my experience successfully implementing Fleet Telemetry for my product:

1. Yes, as long as they are subdomains of your registered domain. I run three Fleet Telemetry servers each with their own subdomain.
2. Yes, I use a cert for each domain but I don't think the vehicle actually validate the DNS. Region makes no difference, and the Fleet Telemetry server is independent of region.
3. If you want seperate partner domains then you need two applications (I think), but you definitely can't have two applications streaming to the same Fleet Telemetry server as it's certificate is meant to be signed by the applications registered key.
