### ISSUE TITLE
Validation failed: Csr is not a valid CSR

### ISSUE THREAD

**Issue by henriksteen** [teslamotors/fleet-telemetry#160]
After following the installation instructions, including the check_csr, I get:
{"response":null,"error":"Validation failed: Csr is not a valid CSR","error_description":"","txid":"8ebdc3bed961facfc62dba400a988185"}

tools/check_csr returns:
----
CSR: elmert.com.csr
Host: www.elmert.com
Public keys are matching

I've regenerated the csr, but no luck.

**Comment by henriksteen** [comment]
The CSR validates correctly on CSR decoders and using OpenSSL.

I presume there is something wrong in the documentation asking to generate it using:
openssl req -out elmert.com.csr -key private-key.pem -subj /CN=elmert.com/ -new

**Comment by Bre77** [comment]
> I presume there is something wrong in the documentation asking to generate it using:

I would expect the check_csr script to be wrong rather than the openssl command. I checked what I could and everything does look correct. Just make sure the CSR is signed with the private key associated with https://www.elmert.com/.well-known/appspecific/com.tesla.3p.public-key.pem

**Comment by patrickdemers6** [comment]
@henriksteen When you're including the CSR in your register request, are you replacing every newline with `\n`? Can you share a more recent TXID? Sorry I'm just seeing this issue.

**Comment by henriksteen** [comment]
@Bre77 No diff between the key on https://www.elmert.com/.well-known/appspecific/com.tesla.3p.public-key.pem and the local public key. I verified it after downloading from the site to be sure.

What's odd is that it claims the CSR is not a valid CSR.

**Comment by henriksteen** [comment]
@patrickdemers6 I did an xxd on it and can confirm that all newlines are 0A only (\n).

The most recent response I got is:
{"response":null,"error":"Validation failed: Csr is not a valid CSR","error_description":"","txid":"30e010dd66f70b9e7b803a36ffb03472"}

Any idea what the txid means?

**Comment by patrickdemers6** [comment]
@henriksteen email me your CSR and client ID at fleetapisupport@tesla.com

I will manually get it attached to your account 👍

**Comment by patrickdemers6** [comment]
If you can also include the exact json payload you're sending, I'll debug what went wrong so we can improve error message.
