### ISSUE TITLE
Kafka partition support needed for scaling

### ISSUE THREAD

**Issue by stx** [teslamotors/fleet-telemetry#169]
We have too many vehicles to make 1 partition <> 1 consumer work.

I've implemented a manual solution for multi-partition support, but it'd be really good if the partition count was configurable. I looked for a way to do this but didn't find any obvious way.

**Comment by KirigiriSuzumiya** [comment]
anything going on with this? looking for answer to same issue

**Comment by KirigiriSuzumiya** [comment]
anything going on with this? looking for answer to same issue
