### ISSUE TITLE
Error CSR when fleet_telemetry_config create

### ISSUE THREAD

**Issue by themarch** [teslamotors/fleet-telemetry#172]
Hi, i have a problem with my CSR when creating the fleet-telemetry config. However, my CSR has been validated because with this third-party token I can use the API in the usual way, like ‘vehicle_data’ for example. 

I've followed all the previous steps to get fleet-telemetry on my server, but I get this error. Thanks in advance

I've noticed that it's only related to my bearer, because I can put anything in the body, it won't change anything. 
Here's my "[URL](bib-data.fr)" : bib-data.fr

<img width="1081" alt="Capture d’écran 2024-05-23 à 11 26 25" src="https://github.com/teslamotors/fleet-telemetry/assets/39468266/764ee13d-c9a2-4988-be47-016468ab9e99">

For example, here I have access to the classic API, my CSR has been accepted and I've already received an email about it.

<img width="1090" alt="Capture d’écran 2024-05-23 à 11 29 34" src="https://github.com/teslamotors/fleet-telemetry/assets/39468266/7c8c8253-97b0-4945-b698-4e7bedbb81ad">

Thanks in advance.

**Comment by Martucci98** [comment]
<img width="1125" alt="Screenshot 2024-05-23 at 13 45 50" src="https://github.com/teslamotors/fleet-telemetry/assets/72300574/d8ba91b1-feae-413f-932e-7fa471908cbd">

To add some information for the request: "{{FLEET_API_URL}}/api/1/vehicles/{{vehicle_tag}}/fleet_telemetry_config"  got a synced but to "true" (see the screen) 

Thank you for your help

**Comment by patrickdemers6** [comment]
@themarch you first setup your account in NA region, but then set up in EU. I've applied the signed certificate to your account in EU so you should now be able to setup fleet-telemetry.

**Comment by patrickdemers6** [comment]
@Martucci98 you are passing a third-party token to the fleet_telemetry_errors endpoint. It requires a partner token. Please see the [Authentication section](https://developer.tesla.com/docs/fleet-api#authentication) of the docs to learn the differences between these tokens.

**Comment by themarch** [comment]
Thanks a lot @patrickdemers6, it's done for this part.

Just one very strange thing. I got this when I wanted to add the public key to the vehicle. However, I do have access to this vehicle, and I can make API calls on it etc. And I've already done the ‘third_party’ and ‘authorization_code’ parts. 

Maybe it's another zone problem? 

![IMG_7614](https://github.com/teslamotors/fleet-telemetry/assets/39468266/da3a17a2-def8-4b83-9b0c-75ad9eeb6ccc)

**Comment by themarch** [comment]
Thanks a lot @patrickdemers6, it's done for this part.

Just one very strange thing. I got this when I wanted to add the public key to the vehicle. However, I do have access to this vehicle, and I can make API calls on it etc. And I've already done the ‘third_party’ and ‘authorization_code’ parts.

Maybe it's another zone problem? (for the translation of the pictures it's : The vehicle cannot be shared.
Adding a virtual key for ‘bib-data.fr’ is prohibited because you have not granted ‘bib-data.fr’ access to your account.)

<img width="354" alt="Capture d’écran 2024-05-27 à 11 47 47" src="https://github.com/teslamotors/fleet-telemetry/assets/39468266/1a640ef0-8403-444d-8959-af3981db2077">
