### ISSUE TITLE
check_server_cert.sh not validate server certificate

### ISSUE THREAD

**Issue by krishR007** [teslamotors/fleet-telemetry#174]
error 20 at 0 depth lookup: unable to get local issuer certificate
error /tmp/tmp.wJir4samcA: verification failed
CN = elvee.app
error 20 at 0 depth lookup: unable to get local issuer certificate
error /tmp/tmp.wJir4samcA: verification failed
-e The server certificate is invalid.

**Comment by patrickdemers6** [comment]
Please describe your setup, steps taken, etc.

**Comment by krishR007** [comment]
1. After tesla fleet confirmation I generate SSL certificate on server:
https://www.digitalocean.com/community/tutorials/how-to-create-a-self-signed-ssl-certificate-for-nginx-in-ubuntu

2. Validate_server.json not validating using check_server_cert.sh. My config file is below:

{
  "hostname": "MY_HOST_NAME",
  "port": "443",
  "ca": "MY_CERTIFICATE_CONTENT"
}

**Comment by krishR007** [comment]
Can you please help me to solve this issue ?
