### ISSUE TITLE
Sending commands via the Telemetry API?

### ISSUE THREAD

**Issue by tapwork** [teslamotors/fleet-telemetry#176]
Since the Fleet API has become practically unusable due to rate limits, I am wondering if the Telemetry API can also be used for commands, such as "api/1/vehicles/(vin)/command/charge_start"? Or is it only for reading data?

**Comment by rileymd88** [comment]
Telemetry is only for receiving data. If you need to run a lot of commands
you can try sending them through Bluetooth instead of over the internet as
there you have no rate limits. The Bluetooth integration is a part of the
vehicle-command package.

**Comment by tapwork** [comment]
Thanks for clarifying. BLE is not an option for us.
