### ISSUE TITLE
Monitor Fleet Telemetry

### ISSUE THREAD

**Issue by Urkman** [teslamotors/fleet-telemetry#187]
Hello,

yesterday my Fleet Telemetry Service inside a Docker Container crashed and I did not notice it :( 
How can I monitor it or restart everything on a crash?

Thanks,
Stefan

**Comment by patrickdemers6** [comment]
At the very least, you can set a restart policy: https://docs.docker.com/compose/compose-file/05-services/#restart

We also expose metrics prometheus metrics. You could alert on the metrics using rules in an external system like Grafana.

Do you have the crash logs? It would be great to prevent the crash from happening for others.
