### ISSUE TITLE
Decode streaming data 

### ISSUE THREAD

**Issue by krishramani01** [teslamotors/fleet-telemetry#195]
Hello, I've created web socket server in nodejs and telemetry connected successfully and data getting in buffer format and I'm trying to decode this data to original data but getting unreadable format.please check screen shot 
![image_2024_08_05T09_34_31_794Z-1](https://github.com/user-attachments/assets/4e7104f4-073a-43d5-b71b-8b8b625d8c11)

**Comment by Bre77** [comment]
The data is sent as protobuf, so you need to decide the raw data using the protobuf definitions in this repo.

**Comment by krishramani01** [comment]
Thanks everything work fine data getting in telemetry server but my question is how to get this data in my server?

**Comment by Bre77** [comment]
You need to learn how to handle protobufs, and implement it in your server using the proto files from this repo. Here is a result I got from a google search. https://thecodebarbarian.com/working-with-protobufs-in-node-js.html

You could also try asking your question on StackOverflow or to an LLM chatbot.

**Comment by krishramani01** [comment]
Is it possible to get telemetry data in my server using Kafka?
