### ISSUE TITLE
Requested Fields being received in chunks vs a single batch

### ISSUE THREAD

**Issue by andrewdevelopz** [teslamotors/fleet-telemetry#199]
I am creating a config using `/api/1/vehicles/fleet_telemetry_config` endpoint and requesting many [Fields](https://github.com/teslamotors/fleet-telemetry/blob/main/protos/vehicle_data.proto), all with `interval_seconds` set to 60.

I am expecting a message to include all the requested Fields, once per minute.
 
There is actually one message in the stored data that have all Fields requested. However, when inspecting the data every other message has Fields coming in chunks. So a message is received every few seconds with 1-10 Fields per message.

Would someone please be able to help so that I can receive all the requested Fields in a single message per minute?

Example Logs:
```
...
{
    "createdAt": "2024-08-23 16:46:27",
    "0": {
        "key": "ScheduledChargingStartTime",
        "value": "some-value"
    }
}
{
    "createdAt": "2024-08-23 16:46:28",
    "0": {
        "key": "ChargePortLatch",
        "value": "some-value"
    }
}
{
    "createdAt": "2024-08-23 16:46:29",
    "0": {
        "key": "ChargeState",
        "value": "some-value"
    },
    "1": {
        "key": "ChargerPhases",
        "value": "some-value"
    }
}
...
```

**Comment by Bre77** [comment]
Are you on a paid subscription? Because I thought Fleet Telemetry was limited to 20 fields with 10 values per minute, and you're exceeding that significantly.

**Comment by andrewdevelopz** [comment]
My mistake, i am using the max Fields allowed.

**Comment by patrickdemers6** [comment]
Data values are sent when the value has changed and the specified interval has passed.

**Comment by andrewdevelopz** [comment]
@patrickdemers6 Ah I see, understood. Thank you for your response.
