### ISSUE TITLE
Connectivity topic "cannot parse invalid wire-format data" with logger

### ISSUE THREAD

**Issue by Bre77** [teslamotors/fleet-telemetry#230]
Just installed [v0.3.4](https://github.com/teslamotors/fleet-telemetry/releases/tag/v0.3.4) and enabled the new connectivity topic, but am getting these errors and ~no connectivity events.~

Edit 1: I am getting both errors, AND connectivity events. I will see if there is some correlation about which work and which dont.

Edit 2: I believe this is only an issue with the "logger" as the issue is resolved as soon as thats removed.

`
{"context":"fleet-telemetry","error":"proto: cannot parse invalid wire-format data","level":"error","metadata":{"receivedat":"1730252498000","timestamp":"0","txid":"4bba9ebc-f4a3-48a8-8475-cb603a784fa4","txtype":"connectivity","version":"0","vin":"redacted"},"msg":"record_logging_error","time":"2024-10-30T01:41:38Z","vin":"redacted"}
`

Relevant config
```json
{
    "log_level": "info",
    "json_log_enable": true,
    "transmit_decoded_records": true,
    "reliable_ack": false,
    "namespace": "na",
    "records": {
        "alerts": [
            "pubsub"
        ],
        "connectivity": [
            "pubsub",
            "logger"
        ],
        "errors": [
            "pubsub"
        ],
        "V": [
            "pubsub"
        ]
    }
}
```

**Comment by Bre77** [comment]
I am starting to suspect that `connectivity` doesnt support `logger`.

**Comment by agbpatro** [comment]
thanks. looks like setting `transmit_decoded_records` to `true` is not compatible with logger. I have submitted a pull request to fix the issue
