### ISSUE TITLE
BUG: Almost everything is a string

### ISSUE THREAD

**Issue by netdata-be** [teslamotors/fleet-telemetry#254]
Is it normal that the data parsed from the probuf are almost all strings?
I would expect  bools and floats but instead they are all send as a string. Requiring extensive parsing on the client side depending on the name of the variable.

**Comment by patrickdemers6** [comment]
Hi @netdata-be, vehicles running 2024.38+ support a new configuration option `prefer_typed`. We will be adding this to the official docs soon.

A truncated version of the configuration you should send to get typed data:
```json
{
  "vins": ["VIN001"],
  "config": {
    "fields": {
      "Soc": {
        "interval_seconds": 1
      }
    },
    "prefer_typed": true
  }
}
```

**Comment by netdata-be** [comment]
@patrickdemers6 what a quality of life improvement ;-)
Just tested it and it indeed seems to fix this ! Thanks for the quick response...
