### ISSUE TITLE
Flatbuffer definitions not committed

### ISSUE THREAD

**Issue by jordan-bonecutter** [teslamotors/fleet-telemetry#49]
Can the definitions for the flatbuffers be committed to the repo? Thanks!

**Comment by aaronpkahn** [comment]
See [messages/tesla](https://github.com/teslamotors/fleet-telemetry/tree/main/messages/tesla)

**Comment by jordan-bonecutter** [comment]
Hey Aaron, maybe I’m looking in the wrong place but is there a flatbuffers schema file which is used to autogen that go code?

https://flatbuffers.dev/flatbuffers_guide_writing_schema.html

I’ve also never worked with flatbuffers before so if that’s not how this works sorry for bugging :)
