### ISSUE TITLE
When creating a third-party token on behalf of a client, a server_error response was received.

### ISSUE THREAD

**Issue by Wiks00** [teslamotors/fleet-telemetry#72]
Greetings.
Recently set up a 3rd party account in FleetAPI and tried to go through the authentication procedure to generate a client token, but encountered a problem at the stage of exchanging the authentication code for the access token and refresh token pair. 

The response  
`{
  "error": "server_error",
  "error_description": "Internal server error"
}`

This could be because we are not planning to generate a partner authentication token and hence skipping the step of generating the public/private key pair for signing commands ?

Note: we are using deeplink as redirect_uri

And an additional question: what is the purpose of redirect_uri in post /token endpoint? [Per RFC 6749](https://www.rfc-editor.org/rfc/rfc6749#section-3) there is no mention of POST /token requiring redirects.

Regards.

**Comment by slashmili** [comment]
About the `server_error` I think you should contact [Tesla fleet support](https://developer.tesla.com/docs/fleet-api#fleet-telemetry) as this repo is not related to the OAuth server.

Just for the record `redirect_url` is part of [RFC6749](https://www.rfc-editor.org/rfc/rfc6749#section-4.1.1). It's optional and it's widely used in many OAuth2 servers.

As for the partner registry, it's mandatory, without that calling Vehicle Data API result in an error like
```
curl https://fleet-api.prd.eu.vn.cloud.tesla.com/api/1/vehicles -H '...'
{"error": "Account XXXXX must be registered please see https://developer.tesla.com/docs/fleet-api#register"}
```
