### ISSUE TITLE
TLS handshake error from 100.94.115.106:21975: EOF

### ISSUE THREAD

**Issue by nitishsingla91** [teslamotors/fleet-telemetry#78]
Experiencing TLS Handshake Error

I've successfully deployed the Fleet Telemetry Service on EKS using the Helm Chart, and I've generated self-signed certificates for both the server and client using the same Certificate Authority (CA). 
Despite a seemingly correct setup, I'm encountering a TLS handshake error when checking the POD logs.

`2023/11/15 22:48:22 http: TLS handshake error from 100.94.115.106:38807: EOF
2023/11/15 22:48:23 http: TLS handshake error from 100.94.115.106:14949: EOF
2023/11/15 22:48:24 http: TLS handshake error from 100.94.115.106:27763: EOF
2023/11/15 22:48:26 http: TLS handshake error from 100.94.115.106:53347: EOF
2023/11/15 22:48:27 http: TLS handshake error from 100.94.115.106:29178: EOF
2023/11/15 22:48:28 http: TLS handshake error from 100.94.115.106:23737: EOF
2023/11/15 22:48:28 http: TLS handshake error from 100.94.115.106:20794: EOF
2023/11/15 22:48:29 http: TLS handshake error from 100.94.115.106:64515: EOF
2023/11/15 22:48:29 http: TLS handshake error from 100.94.115.106:64614: EOF
2023/11/15 22:48:30 http: TLS handshake error from 100.94.115.106:7163: EOF
2023/11/15 22:48:31 http: TLS handshake error from 100.94.115.106:2937: EOF
2023/11/15 22:48:32 http: TLS handshake error from 100.94.115.106:64564: EOF
2023/11/15 22:48:32 http: TLS handshake error from 100.94.115.106:21975: EOF`

Could you provide guidance on troubleshooting this step?

**Comment by slashmili** [comment]
Just for the record, this is because of mTLS requirement on this server. I explained it here: https://github.com/teslamotors/fleet-telemetry/issues/76#issuecomment-1814010334
