### ISSUE TITLE
How is fleet telemetry enabled on a vehicle?

### ISSUE THREAD

**Issue by jbanyer** [teslamotors/fleet-telemetry#85]
How is fleet telemetry enabled on a particular vehicle for a particular third party app?

Is there a step that the driver/owner needs to perform?

Does it build upon the [Third Party App permission mechanism](https://developer.tesla.com/docs/fleet-api#authentication)? 

At what point is the third party `client_config.json` installed and activated on the vehicle?

We still haven't supplied our `client_config.json` to Tesla as there are no instructions as per #41.

Thanks!

**Comment by agbpatro** [comment]
instructions to enable fleet telemetry are present here https://developer.tesla.com/docs/fleet-api#fleet-telemetry
