### ISSUE TITLE
Telemetry FQDN the same as fleet API domain?

### ISSUE THREAD

**Issue by jbanyer** [teslamotors/fleet-telemetry#86]
Should the FQDN for fleet telemetry (as supplied in `client_config.json`) be the same as the `domain` supplied when [registering a public key](https://developer.tesla.com/docs/fleet-api#register) for vehicle pairing (virtual keys for signed commands) in the fleet API?

For example, our fleet API domain (for virtual keys) is `tesla.chargehq.net`.

Should (or MUST?) our FQDN for fleet telemetry be `tesla.chargehq.net`? Or can we use a different subdomain, eg `telemetry.chargehq.net`?

**Comment by Bre77** [comment]
I can confirm now that it does not have to be the same FQDN for Fleet Telemetry. Essentially you setup a certificate authority and can issue certificates for whatever domains you need.

**Comment by jbanyer** [comment]
I have confirmed that the following works:
- registered domain: tesla.chqtest.net
- fleet telemetry FQDN: telemetry.tesla.chqtest.net (a subdomain of the registered domain)

I have not tested FQDNs which are not a subdomain of the registered domain, eg foo.chqtest.net.

**Comment by aaronpkahn** [comment]
It needs to be the same root domain as the registered application. We'll update the FleetAPI docs to state this
